services:
    nanotips-mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: nanotips
            MONGO_INITDB_ROOT_PASSWORD: nanotips
    nanotips-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: nanotips
            ME_CONFIG_MONGODB_ADMINPASSWORD: nanotips
            ME_CONFIG_MONGODB_URL: mongodb://nanotips:nanotips@nanotips-mongo:27017/
            ME_CONFIG_BASICAUTH: false
